### ISSUE TITLE
New "EventBridge Hello World" python throws "Invalid value for `detail`, must not be `None`" upon invoke

### ISSUE THREAD

**Issue by aufbakanleitung** [aws/aws-sam-cli-app-templates#103]
When creating a new "EventBridge Hello World" python application using AWS SAM, it throws the error `Invalid value for detail, must not be None` upon `sam invoke`. This is using these cookiecutter templates so that's why I'm posting the issue here.

I'm running:
- SAM CLI, version 1.23.0. 
- Docker version 20.10.2, build 2291f61
- macOS big Sur, version 11.2.3

Run following commands to replicate:
```bash
sam init
# 1 - AWS Quick Start Templates
# 1 - Zip
# 2 - python3.8
# 2 - EventBridge Hello World
cd hello-world
git init
sam validate
sam build
sam local invoke
```

The full error message is this:
```
$ sam local invoke
Invoking hello_world/app.lambda_handler (python3.8)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-python3.8:rapid-1.23.0.

Mounting /Users/<my_name>/code/persoonlijk/sam-change-detection/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 45b648a6-ba43-4a9b-b7ef-a413eba9548b Version: $LATEST
    raise ValueError("Invalid value for `detail`, must not be `None`")  # noqa: E501
END RequestId: 45b648a6-ba43-4a9b-b7ef-a413eba9548b
REPORT RequestId: 45b648a6-ba43-4a9b-b7ef-a413eba9548b	Init Duration: 0.23 ms	Duration: 125.14 ms	Billed Duration: 200 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
{"errorMessage": "Invalid value for `detail`, must not be `None`", "errorType": "ValueError", "stackTrace": ["  File \"/var/task/hello_world/app.py\", line 29, in lambda_handler\n    awsEvent:AWSEvent = Marshaller.unmarshall(event, AWSEvent)\n", "  File \"/var/task/model/aws/ec2/marshaller.py\", line 76, in unmarshall\n    return cls.__unmarshall_model(data, typeName)\n", "  File \"/var/task/model/aws/ec2/marshaller.py\", line 122, in __unmarshall_model\n    instance = typeName(**kwargs)\n", "  File \"/var/task/model/aws/ec2/aws_event.py\", line 47, in __init__\n    self.detail = detail\n", "  File \"/var/task/model/aws/ec2/aws_event.py\", line 66, in detail\n    raise ValueError(\"Invalid value for `detail`, must not be `None`\")  # noqa: E501\n"]}%
```

**Comment by jfuss** [comment]
This is because you are not sending any data to the local invoke and the function expects that. This is expected because the app assumes the event data fits the model sent by EventBridge. This is called out in the [README](https://github.com/aws/aws-sam-cli-app-templates/blob/master/python3.8/cookiecutter-aws-sam-eventBridge-python/%7B%7Bcookiecutter.project_name%7D%7D/README.md#use-the-sam-cli-to-build-and-test-locally). The command you want to run is `sam local invoke HelloWorldFunction --event events/event.json`.

Closing as this behavior is expected since the incorrect event was passed to the function locally.

**Comment by aufbakanleitung** [comment]
Thanks for the answer. Honestly I forgot about this issue completely 😅
