### ISSUE TITLE
Sam build UnicodeEncodeError: 'charmap' codec can't encode characters in position 348-350: character maps to <undefined>

### ISSUE THREAD

**Issue by mutantmassXXX** [aws/aws-sam-cli-app-templates#114]
I'm using SAM init templates but everytime i try to build it throws a UnicodeEncodeError: 'charmap' codec can't encode characters in position 346-348: character maps to <undefined>.  I tried looking into the src code but cant pinpoint the problem, can someone help me fix my issue?
![SAMError](https://user-images.githubusercontent.com/42291172/119104075-6d5da080-ba4e-11eb-88bb-3a3cd4419cb9.png)

**Comment by hoffa** [comment]
Are you still having this issue?

Looking at the screenshot, I suspect the issue is due to Windows using the [default encoding](https://docs.python.org/3/library/pathlib.html#pathlib.Path.write_text) (which seems to be CP-1252) for `write_text`, and if the characters in the input string can't be represented by the encoding, it fails.

**Comment by jfuss** [comment]
Closing due to no response. Please feel free to create a new issue if this is still happening.
