### ISSUE TITLE
Why is esbuild a direct dependency rather than a dev dependency?

### ISSUE THREAD

**Issue by mikepianka** [aws/aws-sam-cli-app-templates#465]
I noticed in the Node TS examples that esbuild is listed in package.json as a direct dependency rather than a dev dependency. Is there any particular reason for this?

https://github.com/aws/aws-sam-cli-app-templates/blob/9badf4c8ac93e6c5c74a0755c84dbedbf33ef902/nodejs18.x/hello-ts/%7B%7Bcookiecutter.project_name%7D%7D/hello-world/package.json#L16C5-L16C5

**Comment by hawflau** [comment]
Hi @mikepianka thanks for raising the issue.

`sam build` doesn't install dev dependencies. If `esbuild` is not present on `$PATH`, `sam build` would file. In this template, we didn't assume customer has installed `esbuild` on their `$PATH`. That's why it has to be a direct dependency. That said, it's recommended to install `esbuild` on `$PATH` to reduce the Lambda package size

**Comment by mikepianka** [comment]
Ok thank you for that explanation! I figured there had to be a reason.
